language: elixir
elixir:
  - 1.4.5
otp_release:
  - 20.0
install:
  - mix local.hex --force
  - mix local.rebar --force
  - mix deps.get
script:
  - mix test
notifications:
  recipients:
    - serneum@gmail.com
